# -*- coding: utf-8 -*-
"""code.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1W_233t6XR3dv1ngLGMQhYXYAI0AHEikE

#Zeinab Dast Mozd (2323135)
#  CE807-7-SU : Text Analytics
#  Assignment  : Code
"""

!pip install transformers

""" # Import all require libraries.

"""

import os
import numpy as np
import pandas as pd
import re
import pickle

from collections import Counter
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix, classification_report

# Download NLTK resources which is needed
import nltk
nltk.download('punkt')
nltk.download('stopwords')

"""### Student id"""

student_id = 2323135 # this is an interger number and it is my registeration id
# set same seeds for all libraries

#numpy seed
np.random.seed(student_id)

"""# Common Codes


*   Data read
*   Performance Matrics
*   Print Dataset Statistics
*   Saving model and output
*   Loading Model and output




"""

# Mount Google Drive
from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

"""### Data read function"""

def load_data(train_path, valid_path, test_path):
    """
    Load training, validation, and test datasets from specified file paths.

    Parameters:
    train_path (str): Path to the training dataset CSV file.
    valid_path (str): Path to the validation dataset CSV file.
    test_path (str): Path to the test dataset CSV file.

    Returns:
    tuple: A tuple containing three DataFrames (train_df, valid_df, test_df).
    """
    # Load the data into DataFrames
    train_df = pd.read_csv(train_path)
    valid_df = pd.read_csv(valid_path)
    test_df = pd.read_csv(test_path)

    # Return the DataFrames  valid train and test as a tuple
    return train_df, valid_df, test_df

"""### Performance Matrics function"""

def print_performance_metrics(y_true, y_pred):
    """
    Print performance metrics for a classification model.

    Parameters:
    y_true (list or array-like): True labels.
    y_pred (list or array-like): Predicted labels by the model.
    """
    # Calculate metrics
    accuracy = accuracy_score(y_true, y_pred)
    precision = precision_score(y_true, y_pred, average='weighted')
    recall = recall_score(y_true, y_pred, average='weighted')
    f1 = f1_score(y_true, y_pred, average='weighted')
    conf_matrix = confusion_matrix(y_true, y_pred)
    class_report = classification_report(y_true, y_pred)

    # Print metrics
    print("Accuracy:", accuracy)
    print("Precision (weighted):", precision)
    print("Recall (weighted):", recall)
    print("F1 Score (weighted):", f1)
    print("\nConfusion Matrix:")
    print(conf_matrix)
    print("\nClassification Report:")
    print(class_report)

"""###  Dataset Statistics function"""

import pandas as pd

def print_dataset_statistics(df, text_column, label_column=None):
    """
    Print statistics for a text dataset.

    Parameters:
    df (pd.DataFrame): The dataset in the form of a DataFrame.
    text_column (str): The name of the column containing text data.
    label_column (str, optional): The name of the column containing labels. If provided, statistics about labels will be printed.
    """
     # Fill missing values
    df[text_column] = df[text_column].fillna('')
    if label_column:
        df[label_column] = df[label_column].fillna(df[label_column].mode()[0] if df[label_column].dtype == 'object' else df[label_column].median())

    # Number of samples
    num_samples = len(df)

    # Text length statistics
    df['text_length'] = df[text_column].apply(len)# Calculate the length of each text
    avg_text_length = df['text_length'].mean()# Compute the average text length
    min_text_length = df['text_length'].min() # Find the minimum text length
    max_text_length = df['text_length'].max()# Find the maximum text length

    # Word count statistics
    df['word_count'] = df[text_column].apply(lambda x: len(x.split()))# Calculate the number of words in each text entry
    avg_word_count = df['word_count'].mean()# Compute the average word count
    min_word_count = df['word_count'].min()# Find the minimum word count
    max_word_count = df['word_count'].max()# Find the maximum word count

    # Print statistics
    print(f"Number of Samples: {num_samples}")
    print(f"Average Text Length: {avg_text_length:.2f}")
    print(f"Minimum Text Length: {min_text_length}")
    print(f"Maximum Text Length: {max_text_length}")
    print(f"Average Word Count: {avg_word_count:.2f}")
    print(f"Minimum Word Count: {min_word_count}")
    print(f"Maximum Word Count: {max_word_count}")

    # Print label statistics if label_column is provided
    if label_column:
        num_unique_labels = df[label_column].nunique()
        print(f"Number of Unique Labels: {num_unique_labels}")

        label_counts = df[label_column].value_counts()
        print("\nLabel Distribution:")
        print(label_counts)

"""### Saving model function"""

import joblib

def save_model_and_vectorizer(model, vectorizer, model_path, vectorizer_path):
    """
    Save any given model and vectorizer to the specified file paths.

    Parameters:
    - model: The trained model to be saved.
    - vectorizer: The trained vectorizer to be saved.
    - model_path: The file path where the model should be saved.
    - vectorizer_path: The file path where the vectorizer should be saved.
    """
    # Save the model to my gdrive in the specific given path
    joblib.dump(model, model_path)
    print(f"Model saved to {model_path}.")

    # Save the vectorizer to my gdrive in the specific given path
    joblib.dump(vectorizer, vectorizer_path)
    print(f"Vectorizer saved to {vectorizer_path}.")

"""### Loading Model function"""

import joblib

def load_model_and_vectorizer(model_path, vectorizer_path):
    """
    Load any given model and vectorizer from the specified file paths.

    Parameters:
    - model_path: The file path where the model is saved.
    - vectorizer_path: The file path where the vectorizer is saved.

    Returns:
    - model: The loaded model.
    - vectorizer: The loaded vectorizer.
    """
    # Load the model from my gdrive from the specific given path
    model = joblib.load(model_path)
    print(f"Model loaded from {model_path}.")

    # Load the vectorizer from my gdrive from the specific given path
    vectorizer = joblib.load(vectorizer_path)
    print(f"Vectorizer loaded from {vectorizer_path}.")

    return model, vectorizer

"""### Save the output of the model prediction to test.csv function"""

import pandas as pd

def save_predictions_to_csv(predictions, csv_path, output_column):
    """
    Save the predictions to a specific column in a CSV file.

    Parameters:
    - predictions: A list or array of predictions to be saved.
    - csv_path: The path to the CSV file where predictions will be saved.
    - output_column: The column name where predictions should be saved.
    """
    # Load the existing CSV file
    df = pd.read_csv(csv_path)

    # Add predictions to the specified column
    df[output_column] = predictions

    # Save the updated DataFrame back to CSV
    df.to_csv(csv_path, index=False)
    print(f"Predictions saved to column '{output_column}' in {csv_path}.")

# Your Code(s)

"""# Method Unsupervised


*   Data reading
*   Data clearning, if any
*   Convert data to vector/tokenization/vectorization
*   Model Declaration/Initialization/building
*   Training and validation of the model using training and validation dataset
*   Save the trained model
*   Load and Test the model on testing set
*   Save the output of the model

####  Data cleaning and tokanizationg function
"""

import pandas as pd
import re
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
import nltk

def preprocess_text(df, text_column='text'):
    """
    Preprocesses the text data in a DataFrame by performing the following steps:
    1. Handling missing values
    2. Cleaning text (lowercasing, removing digits, and punctuation)
    3. Tokenizing and removing stop words

    Parameters:
    df (pd.DataFrame): The DataFrame containing the text data.
    text_column (str): The column name containing the text to preprocess.

    Returns:
    pd.DataFrame: The DataFrame with an additional column 'cleaned_text' containing the processed text.
    """
    # Download NLTK resources for stopwords and tokenization in case some thing went wrong and it is need it.
    nltk.download('stopwords')
    nltk.download('punkt')

    # Fill missing values in the specified text column with empty strings
    df[text_column] = df[text_column].fillna('')

    # Define function to clean text: lowercasing, removing digits, and punctuation
    def clean_text(text):
        """
        Cleans the text by:
        - Converting to lowercase
        - Removing digits
        - Removing punctuation

        Parameters:
        text (str): The text to clean.

        Returns:
        str: The cleaned text.
        """
        if isinstance(text, str):
            text = text.lower()  # Convert to lowercase
            text = re.sub(r'\d+', '', text)  # Remove digits
            text = re.sub(r'[^\w\s]', '', text)  # Remove punctuation
        return text

    # Apply text cleaning function to the specified text column
    df['cleaned_text'] = df[text_column].apply(clean_text)

    # Define stop words set from NLTK
    stop_words = set(stopwords.words('english'))

    # Define function to tokenize text and remove stop words
    def tokenize_and_filter(text):
        """
        Tokenizes the text and removes stop words.

        Parameters:
        text (str): The cleaned text to tokenize and filter.

        Returns:
        str: The filtered text with stop words removed.
        """
        tokens = word_tokenize(text)  # Tokenize text
        filtered_tokens = [word for word in tokens if word not in stop_words]  # Remove stop words
        return ' '.join(filtered_tokens)  # Rejoin tokens into a single string

    # Apply tokenization and stop words removal to the cleaned text
    df['cleaned_text'] = df['cleaned_text'].apply(tokenize_and_filter)

    return df
    """
    other steps for cleaning the data was used in order to inhance the performance.
    However i noticed that there is not effect and they did not pose any positive improvement.
    as a result, i opt to remove them as the above ones is sufficient
        # Remove special formatting tokens and any metadata markers
        text = re.sub(r'\b(NEWLINE_TOKEN|SDATA_\d+|EDATA_\d+)\b', '', text)
        # Remove multiple spaces with a single space
        text = re.sub(r'\s+', ' ', text).strip()
        # Remove URLs
        text = re.sub(r'http\S+|www\.\S+', '', text)
        # Remove emails
        text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', '', text)
        """

"""#### Calling the reading data function"""

# Specify the paths to my data files
train_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/train.csv'
valid_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/valid.csv'
test_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/test.csv'


# Load data using the function
train_df, valid_df, test_df = load_data(train_path, valid_path, test_path)

# Display the first few rows of each DataFrame to verify
print("Training Data:")
print(train_df.head())
print("\nValidation Data:")
print(valid_df.head())
print("\nTest Data:")
print(test_df.head())

"""#### Calling the preprosses text function for cleaning and tokenazing"""

# Preprocess the train, validation, and test datasets
train_data = preprocess_text(train_df, text_column='text')
valid_data = preprocess_text(valid_df, text_column='text')
test_data = preprocess_text(test_df, text_column='text')

"""#### Vectorizing the data"""

# Convert text data to TF-IDF features
vectorizer = TfidfVectorizer(stop_words='english')

# Fit on train data and transform all datasets (validation and test)
train_unsup = vectorizer.fit_transform(train_data['cleaned_text'])
X_valid = vectorizer.transform(valid_data['cleaned_text'])
test_unsup = vectorizer.transform(test_data['cleaned_text'])

"""## Training Method Unsupervised Code

#### Initializing the Model, train and save the trained model
"""

# Initialize KMeans with two clusters and set random_state for reproducibility equal to student id
kmeans = KMeans(n_clusters=2, random_state=student_id)

# Fit KMeans on training data
kmeans.fit(train_unsup)
# Save the best model and vectorizer
model_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/model/2323135/Model_Unsup/KMeans_model.pkl'
vectorizer_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/model/2323135/Model_Unsup/tfidf_vectorizer.pkl'
save_model_and_vectorizer(kmeans, vectorizer, model_path, vectorizer_path)

"""#### Predicting on the train set"""

# Pridicting on the train set
train_labels = kmeans.predict(train_unsup)
# Count positive and negative values
prediction_counts = Counter(train_labels)
num_positive = prediction_counts.get(0, 0)  # 0 means positive
num_negative = prediction_counts.get(1, 0)  # 1 means negative

# Print the counts
print(f"Number of Positive Predictions: {num_positive}")
print(f"Number of Negative Predictions: {num_negative}")

"""#### Evaluating using validation set"""

# Predict clusters on validation set
valid_labels = kmeans.predict(X_valid)

# Convert true labels to numeric to match the predicted label type
y_true = valid_df['sentiment']
label_encoder = LabelEncoder()
true_labels_numeric = label_encoder.fit_transform(y_true)

# Count the number of samples in each cluster
cluster_counts = Counter(valid_labels)

# Determine which cluster should be positive and which negative
positive_cluster = cluster_counts.most_common(1)[0][0]  # Cluster with more rows
negative_cluster = 1 - positive_cluster  # Assuming only two clusters: 0 and 1

# Map the cluster labels: the cluster with more samples is positive, the other is negative
predicted_labels = [1 if label == positive_cluster else 0 for label in valid_labels]

# Print metrics comparing the true labels with the remapped predicted labels
print_performance_metrics(true_labels_numeric, predicted_labels)

"""# Count positive and negative values
prediction_counts = Counter(valid_labels)
num_positive = prediction_counts.get(1, 0)  # 1 means positive
num_negative = prediction_counts.get(0, 0)  # 0 means negative

# Print the counts
print(f"Number of Positive Predictions: {num_positive}")
print(f"Number of Negative Predictions: {num_negative}")

## Testing Method Unsupervised Code

#### loading the saved model
"""

model_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/model/2323135/Model_Unsup/KMeans_model.pkl'
vectorizer_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/model/2323135/Model_Unsup/tfidf_vectorizer.pkl'

model, vectorizer = load_model_and_vectorizer(model_path, vectorizer_path)

"""#### Predict on test and saving the output to out_label_model_unsup"""

# Predict clusters on test
test_labels = kmeans.predict(test_unsup)
# declareing the path
csv_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/test.csv'
output_column = 'out_label_model_unsup'  # the disered column
# calling the saving output function
save_predictions_to_csv(test_labels, csv_path, output_column)

# Read the CSV file into a DataFrame
df = pd.read_csv('/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/test.csv')

# Display the first 5 rows
print(df.head(5))

# Count positive and negative values
prediction_counts = Counter(test_labels)
num_positive = prediction_counts.get(0, 0)  # 0 means positive
num_negative = prediction_counts.get(1, 0)  # 1 means negative

# Print the counts
print(f"Number of Positive Predictions: {num_positive}")
print(f"Number of Negative Predictions: {num_negative}")

"""## Method Unsupervised End

# Method Discriminative


*   Data reading
*   Data clearning, if any
*   Convert data to vector/tokenization/vectorization
*   Model Declaration/Initialization/building
*   Training and validation of the model using training and validation dataset
*   Save the trained model
*   Load and Test the model on testing set
*   Save the output of the model

#### Data cleaning and tokanizationg
"""

def preprocess_text(df, text_column='text'):
    """
    Preprocesses the text data in a DataFrame.

    Input:
    -The input DataFrame containing the text data.
    -The name of the column in the DataFrame that contains the text data to be processed. Default is 'text'.

    Output:
    -A DataFrame with an additional column 'cleaned_text' that contains the processed text data.

    Functionality:
    1. **Missing Value Handling**:
       - Checks for missing values in the specified text column and prints the count of missing values.
       - Fills missing values in the text column with empty strings to avoid errors during text processing.

    2. **Text Cleaning**:
       - Converts the text to lowercase to ensure uniformity.
       - Removes all digits from the text using regular expressions.
       - Strips out punctuation and special characters, leaving only alphabetic characters and spaces.

    3. **Tokenization and Stop Words Removal**:
       - Defines a set of stop words from the NLTK library's English stopwords.
       - Tokenizes the cleaned text into individual words.
       - Removes stop words from the tokenized text, keeping only meaningful words.
       - Joins the filtered words back into a single string for each text entry.

    4. **Output**:
       - The original DataFrame with an additional column 'cleaned_text' that contains the processed text.

    Note:
    - The function assumes that the NLTK library is installed and that the necessary datasets for stop words and tokenization are downloaded.
    """

    # Check for missing values
    missing_values_count = df[text_column].isnull().sum()
    print(f"Number of missing values in '{text_column}' column before filling: {missing_values_count}")

    # Fill missing values in text column with empty strings
    df[text_column] = df[text_column].fillna('')

    # Define text cleaning function
    def clean_text(text):
        if isinstance(text, str):
            text = text.lower()
            text = re.sub(r'\d+', '', text)
            text = re.sub(r'[^\w\s]', '', text)
        return text

    # Apply cleaning function
    df['cleaned_text'] = df[text_column].apply(clean_text)

    # Define stop words
    stop_words = set(stopwords.words('english'))

    # Define tokenization and filtering function
    def tokenize_and_filter(text):
        tokens = word_tokenize(text)
        filtered_tokens = [word for word in tokens if word not in stop_words]
        return ' '.join(filtered_tokens)

    # Apply tokenization and filtering
    df['cleaned_text'] = df['cleaned_text'].apply(tokenize_and_filter)

    return df
    """
    other steps for cleaning the data was used in order to inhance the performance.
    However i noticed that there is not effect and they did not pose any positive improvement.
    as a result, i opt to remove them as the above ones is sufficient
        # Remove special formatting tokens and any metadata markers
        text = re.sub(r'\b(NEWLINE_TOKEN|SDATA_\d+|EDATA_\d+)\b', '', text)
        # Remove multiple spaces with a single space
        text = re.sub(r'\s+', ' ', text).strip()
        # Remove URLs
        text = re.sub(r'http\S+|www\.\S+', '', text)
        # Remove emails
        text = re.sub(r'\b[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Z|a-z]{2,}\b', '', text)
        """

"""#### Data vectorizing"""

def vectorize_data(train_df, valid_df, test_df, text_column='cleaned_text', sentiment_column='sentiment'):
    """
    Vectorizes text data using TF-IDF and prepares it for model training, validation, and testing.

    Input:
    - train_df (pd.DataFrame): The DataFrame containing the training data.
    - valid_df (pd.DataFrame): The DataFrame containing the validation data.
    - test_df (pd.DataFrame): The DataFrame containing the test data.
    - text_column (str): The column name in the DataFrames that contains the cleaned text data. Default is 'cleaned_text'.
    - sentiment_column (str): The column name in the DataFrames that contains the sentiment labels. Default is 'sentiment'.

    Output:
    - X_train_tfidf (scipy.sparse.csr.csr_matrix): The TF-IDF vectorized features of the training set.
    - y_train (pd.Series): The labels for the training set.
    - X_valid_tfidf (scipy.sparse.csr.csr_matrix): The TF-IDF vectorized features of the validation set.
    - y_valid (pd.Series): The labels for the validation set.
    - X_test_tfidf (scipy.sparse.csr.csr_matrix): The TF-IDF vectorized features of the test set.
    - y_test_dis (pd.Series): The 'out_label_model_dis' labels for the test set.
    - y_test_unsup (pd.Series): The 'out_label_model_unsup' labels for the test set.
    - tfidf_vectorizer (TfidfVectorizer): The TF-IDF vectorizer object, fitted on the training data.

    Functionality:
    1. **Text Preprocessing**:
       - Calls `preprocess_text` on the training, validation, and test DataFrames to clean and prepare the text data.

    2. **Feature and Label Separation**:
       - Extracts features (text data) and labels from the DataFrames.
       - The features are extracted from the column specified by `text_column`.
       - The labels for training and validation are from the `sentiment_column`.
       - The test set has two different label columns: 'out_label_model_dis' and 'out_label_model_unsup'.

    3. **TF-IDF Vectorization**:
       - Initializes a `TfidfVectorizer` with English stop words to transform text data into numerical form.
       - Fits the vectorizer on the training data and transforms it into TF-IDF features.
       - Uses the same vectorizer to transform the validation and test data, ensuring consistency in feature representation.

    4. **Return Values**:
       - Returns the TF-IDF transformed features and the corresponding labels for training, validation, and testing, along with the fitted TF-IDF vectorizer.
    """

    # Preprocess text data
    train_df = preprocess_text(train_df, text_column)
    valid_df = preprocess_text(valid_df, text_column)
    test_df = preprocess_text(test_df, text_column)

    # Split data into features and labels
    X_train = train_df[text_column]
    y_train = train_df[sentiment_column]
    X_valid = valid_df[text_column]
    y_valid = valid_df[sentiment_column]
    X_test = test_df[text_column]
    y_test_dis = test_df['out_label_model_dis']
    y_test_unsup = test_df['out_label_model_unsup']

    # Initialize TF-IDF Vectorizer
    tfidf_vectorizer = TfidfVectorizer(stop_words='english')

    # Fit and transform training data
    X_train_tfidf = tfidf_vectorizer.fit_transform(X_train)

    # Transform validation and test data using the same vectorizer
    X_valid_tfidf = tfidf_vectorizer.transform(X_valid)
    X_test_tfidf = tfidf_vectorizer.transform(X_test)

    return X_train_tfidf, y_train, X_valid_tfidf, y_valid, X_test_tfidf, y_test_dis, y_test_unsup, tfidf_vectorizer

"""#### Calling the reading function"""

# Specify the paths to my data files
train_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/train.csv'
valid_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/valid.csv'
test_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/test.csv'


# Load data using the function
train_df, valid_df, test_df = load_data(train_path, valid_path, test_path)

# Optional: Display the first few rows of each DataFrame to verify
print("Training Data:")
print(train_df.head())
print("\nValidation Data:")
print(valid_df.head())
print("\nTest Data:")
print(test_df.head())

"""#### Calling the cleaning and tokanization fucntion and vectorzing function"""

# Call the function for each dataframe
train_df_cleaned = preprocess_text(train_df, text_column='text')
valid_df_cleaned = preprocess_text(valid_df, text_column='text')
test_df_cleaned = preprocess_text(test_df, text_column='text')

# Vectorize data
train_dis, y_train, X_valid_tfidf, y_valid, test_dis, y_test_dis, y_test_unsup, tfidf_vectorizer = vectorize_data(train_df, valid_df, test_df, text_column='cleaned_text', sentiment_column='sentiment')
train_dis.shape

"""#### Calling print_dataset_statistics function"""

print_dataset_statistics(train_df, text_column='text', label_column='sentiment')
print_dataset_statistics(valid_df, text_column='text', label_column='sentiment')
#print_dataset_statistics(test_df, text_column='text', label_column='sentiment')
test_df.shape

"""## Training Method Discriminative

#### Model initialization
"""

# Define the model and hyperparameters for tuning
svm = SVC(random_state=student_id)
param_grid = {
    'C': [0.9, 1, 1.1, 1.777],  # Regularization parameter
    'kernel': ['linear', 'rbf'],  # Kernel type
    'gamma': ['scale', 'auto']  # Kernel coefficient for 'rbf'
}

"""#### Training using training dataset and Save the trained model


"""

# Perform Grid Search with Cross-Validation
grid_search = GridSearchCV(svm, param_grid, cv=5, scoring='accuracy')
grid_search.fit(train_dis, y_train)
# Best parameters from Grid Search
print("Best parameters found:", grid_search.best_params_)
best_svm = grid_search.best_estimator_
# Save the best model and vectorizer
model_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/model/2323135/Model_Dis/svm_model.pkl'
vectorizer_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/model/2323135/Model_Dis/tfidf_vectorizer.pkl'
save_model_and_vectorizer(best_svm, tfidf_vectorizer, model_path, vectorizer_path)

y_TRAIN_pred = best_svm.predict(train_dis)
# Count positive and negative values
prediction_counts = Counter(y_TRAIN_pred)
num_positive = prediction_counts.get(1, 0)  # 1 means positive
num_negative = prediction_counts.get(0, 0)  # 0 means negative

# Print the counts
print(f"Number of Positive Predictions: {num_positive}")
print(f"Number of Negative Predictions: {num_negative}")
y_TRAIN_pred

"""#### Evaluationg using validation dataset"""

# 4. Evaluate on Validation Set
y_valid_pred = best_svm.predict(X_valid_tfidf)
print("Validation Accuracy:", print_performance_metrics(y_valid, y_valid_pred))
print("Validation Classification Report:\n", print_performance_metrics(y_valid, y_valid_pred))

"""## Testing Method Discriminative

#### Loading the model by calling loading function
"""

model_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/model/2323135/Model_Dis/svm_model.pkl'
vectorizer_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/model/2323135/Model_Dis/tfidf_vectorizer.pkl'

model, vectorizer = load_model_and_vectorizer(model_path, vectorizer_path)

"""#### Function to predict on test dataset"""

def predict_with_model(model, X_test_tfidf):
    # Make predictions
    predictions = model.predict(X_test_tfidf)
    return predictions

"""#### Calling the previous function of prediction on test dataset"""

# Predict with the loaded model
y_pred = predict_with_model(model, test_dis)

# Print the predictions
#print("Predictions:", y_pred)

# Count positive and negative values
prediction_counts = Counter(y_pred)
num_positive = prediction_counts.get('positive', 1)  # 1 means positive
num_negative = prediction_counts.get('negative', 0)  # 0 means negative

# Print the counts
print(f"Number of Positive Predictions: {num_positive}")
print(f"Number of Negative Predictions: {num_negative}")

"""#### Save the output of the model in out_label_model_dis column"""

# declareing the path
csv_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/test.csv'
output_column = 'out_label_model_dis'  # the disered column
# calling the saving output function
save_predictions_to_csv(y_pred, csv_path, output_column)

"""## Discriminative Method  End

# Other Method/model Start

##Neural network model
#### fully connected neural network (FCNN)
"""

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import LabelEncoder
import random

# Set the seed for reproducibility using the student ID
student_id = 2323135
torch.manual_seed(student_id)
np.random.seed(student_id)
random.seed(student_id)
if torch.cuda.is_available():
    torch.cuda.manual_seed_all(student_id)

# Define SentimentNN class
class SentimentNN(nn.Module):
    def __init__(self, input_size, hidden_size, output_size):
        super(SentimentNN, self).__init__()
        self.fc1 = nn.Linear(input_size, hidden_size)
        self.relu = nn.ReLU()
        self.fc2 = nn.Linear(hidden_size, output_size)
        self.sigmoid = nn.Sigmoid()

    def forward(self, x):
        out = self.fc1(x)
        out = self.relu(out)
        out = self.fc2(out)
        out = self.sigmoid(out)
        return out

# Assuming vectorize_data function is implemented
X_train_tfidf, y_train, X_valid_tfidf, y_valid, X_test_tfidf, y_test_dis, y_test_unsup, tfidf_vectorizer = vectorize_data(
    train_df, valid_df, test_df, text_column='cleaned_text', sentiment_column='sentiment')

# Convert labels to numeric values (if not already numeric)
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_valid = label_encoder.transform(y_valid)

# Define input, hidden, and output sizes
input_size = X_train_tfidf.shape[1]
hidden_size = 128
output_size = 1  # For binary classification

# Instantiate the model
model = SentimentNN(input_size, hidden_size, output_size)

# Convert datasets to torch tensors and create DataLoaders
train_dataset = TensorDataset(torch.tensor(X_train_tfidf.toarray(), dtype=torch.float32),
                              torch.tensor(y_train, dtype=torch.float32))
train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

valid_dataset = TensorDataset(torch.tensor(X_valid_tfidf.toarray(), dtype=torch.float32),
                              torch.tensor(y_valid, dtype=torch.float32))
valid_loader = DataLoader(valid_dataset, batch_size=32, shuffle=False)

# Loss and optimizer
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
num_epochs = 5
for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    for batch_x, batch_y in train_loader:
        # Convert labels to float
        batch_y = batch_y.float()

        # Forward pass
        outputs = model(batch_x).squeeze(1)  # Squeeze only the last dimension if it's 1
        loss = criterion(outputs, batch_y)

        # Backward and optimize
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {running_loss/len(train_loader):.4f}')

from sklearn.metrics import accuracy_score

# Validation
model.eval()
with torch.no_grad():
    valid_predictions = []
    valid_labels = []
    for batch_x, batch_y in valid_loader:
        outputs = model(batch_x)
        predicted = (outputs.squeeze() >= 0.5).float()
        valid_predictions.extend(predicted.cpu().numpy())
        valid_labels.extend(batch_y.cpu().numpy())

# Evaluate validation accuracy
valid_accuracy = accuracy_score(valid_labels, valid_predictions)
print(f'Validation Accuracy: {valid_accuracy:.4f}')
print(print_performance_metrics(valid_labels, valid_predictions))

# Predict on the test set
X_test_tensor = torch.tensor(X_test_tfidf.toarray(), dtype=torch.float32)  # Convert test data to tensor
with torch.no_grad():
    test_outputs = model(X_test_tensor)
    test_predictions = (test_outputs.squeeze() >= 0.5).float()
    y_pred = test_predictions.cpu().numpy()

# Print test predictions
print("Predictions on test set:", y_pred)

# Count positive and negative values
prediction_counts = Counter(test_labels)
num_positive = prediction_counts.get(0, 0)  # 1 means positive
num_negative = prediction_counts.get(1, 0)  # 0 means negative

# Print the counts
print(f"Number of Positive Predictions: {num_positive}")
print(f"Number of Negative Predictions: {num_negative}")

"""# cnn model
##### i used cnn but it is taking too long time i reduec the complexity of it but still it takes time and it is computationall heavy that is why i decided to not use it and remain with the svm and fcnn

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, TensorDataset
from sklearn.preprocessing import LabelEncoder
from sklearn.metrics import accuracy_score
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer



# Set the seed for reproducibility
student_id = 2323135
torch.manual_seed(student_id)
np.random.seed(student_id)

# Define CNN class for sentiment analysis
class SentimentCNN(nn.Module):
    def __init__(self, vocab_size, embedding_dim, num_classes):
        super(SentimentCNN, self).__init__()
        self.embedding = nn.Embedding(vocab_size, embedding_dim)
        self.conv1 = nn.Conv2d(1, 100, kernel_size=(3, embedding_dim))
        self.conv2 = nn.Conv2d(1, 100, kernel_size=(4, embedding_dim))
        self.conv3 = nn.Conv2d(1, 100, kernel_size=(5, embedding_dim))
        self.pool = nn.AdaptiveMaxPool1d(1)
        self.fc1 = nn.Linear(3 * 100, num_classes)

    def forward(self, x):
        x = self.embedding(x)
        x = x.unsqueeze(1)  # Add channel dimension

        x1 = torch.relu(self.conv1(x)).squeeze(3)
        x2 = torch.relu(self.conv2(x)).squeeze(3)
        x3 = torch.relu(self.conv3(x)).squeeze(3)

        x1 = self.pool(x1).squeeze(2)
        x2 = self.pool(x2).squeeze(2)
        x3 = self.pool(x3).squeeze(2)

        x = torch.cat((x1, x2, x3), dim=1)
        x = self.fc1(x)
        return torch.sigmoid(x)

# Specify the paths to your data files
train_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/train.csv'
valid_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/valid.csv'
test_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/test.csv'


# Load data using the function
train_df, valid_df, test_df = load_data(train_path, valid_path, test_path)

# Optional: Display the first few rows of each DataFrame to verify
print("Training Data:")
print(train_df.head())
print("\nValidation Data:")
print(valid_df.head())
print("\nTest Data:")
print(test_df.head())

# Preprocess the train, validation, and test datasets
train_df = preprocess_text(train_df, text_column='text')
valid_df = preprocess_text(valid_df, text_column='text')
test_df = preprocess_text(test_df, text_column='text')


# Example data processing function
def vectorize_data(train_df, valid_df):
    tfidf_vectorizer = TfidfVectorizer()
    X_train_tfidf = tfidf_vectorizer.fit_transform(train_df['cleaned_text'])
    X_valid_tfidf = tfidf_vectorizer.transform(valid_df['cleaned_text'])
    return X_train_tfidf, train_df['sentiment'], X_valid_tfidf, valid_df['sentiment'], tfidf_vectorizer



# Dummy data loading and vectorization
# Replace with actual data loading logic
X_train_tfidf, y_train, X_valid_tfidf, y_valid, tfidf_vectorizer = vectorize_data(
    train_df, valid_df
)

# Convert labels to numeric values
label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(y_train)
y_valid = label_encoder.transform(y_valid)

# Define parameters
vocab_size = len(tfidf_vectorizer.vocabulary_) + 1
embedding_dim = 300
num_classes = 1

# Instantiate the model
model = SentimentCNN(vocab_size, embedding_dim, num_classes)

# Convert datasets to torch tensors and create DataLoaders
def create_dataloader(X, y, batch_size=32):
    dataset = TensorDataset(torch.tensor(X.toarray(), dtype=torch.long), torch.tensor(y, dtype=torch.float32))
    return DataLoader(dataset, batch_size=batch_size, shuffle=True)

train_loader = create_dataloader(X_train_tfidf, y_train)
valid_loader = create_dataloader(X_valid_tfidf, y_valid, batch_size=32)

# Loss and optimizer
criterion = nn.BCELoss()
optimizer = optim.Adam(model.parameters(), lr=0.001)

# Training loop
num_epochs = 5
for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    for batch_x, batch_y in train_loader:
        outputs = model(batch_x).squeeze(1)
        loss = criterion(outputs, batch_y)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {running_loss/len(train_loader):.4f}')

# Validation
model.eval()
valid_predictions, valid_labels = [], []
with torch.no_grad():
    for batch_x, batch_y in valid_loader:
        outputs = model(batch_x)
        predicted = (outputs.squeeze() >= 0.5).float()
        valid_predictions.extend(predicted.cpu().numpy())
        valid_labels.extend(batch_y.cpu().numpy())

# Evaluate validation accuracy
valid_accuracy = accuracy_score(valid_labels, valid_predictions)
print(f'Validation Accuracy: {valid_accuracy:.4f}')
"
"""

y_pred[196]

"""from transformers import T5Tokenizer, T5ForConditionalGeneration, AdamW
from torch.utils.data import DataLoader, TensorDataset
import torch
from sklearn.metrics import accuracy_score

# Define model and tokenizer
model_name = "t5-small"
tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

# Function to prepare the data for T5
def prepare_data(df, text_column, target_column):
    inputs, targets = [], []
    for _, row in df.iterrows():
        input_text = f"classify: {row[text_column]}"
        target_text = "positive" if row[target_column] == 1 else "negative"
        inputs.append(input_text)
        targets.append(target_text)
    return inputs, targets

# Assuming train_df, valid_df, and test_df are your dataframes
train_inputs, train_targets = prepare_data(train_df, 'cleaned_text', 'sentiment')
valid_inputs, valid_targets = prepare_data(valid_df, 'cleaned_text', 'sentiment')

# Tokenizing the data
def tokenize(inputs, targets, tokenizer, max_length=512):
    input_encodings = tokenizer(inputs, truncation=True, padding=True, max_length=max_length, return_tensors="pt")
    target_encodings = tokenizer(targets, truncation=True, padding=True, max_length=2, return_tensors="pt")

    input_ids = input_encodings['input_ids']
    attention_mask = input_encodings['attention_mask']
    labels = target_encodings['input_ids']
    return TensorDataset(input_ids, attention_mask, labels)

train_dataset = tokenize(train_inputs, train_targets, tokenizer)
valid_dataset = tokenize(valid_inputs, valid_targets, tokenizer)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
valid_loader = DataLoader(valid_dataset, batch_size=16, shuffle=False)

# Training loop
optimizer = AdamW(model.parameters(), lr=3e-5)
num_epochs = 3

model.train()
for epoch in range(num_epochs):
    total_loss = 0
    for batch in train_loader:
        input_ids, attention_mask, labels = batch
        optimizer.zero_grad()
        outputs = model(input_ids=input_ids, attention_mask=attention_mask, labels=labels)
        loss = outputs.loss
        loss.backward()
        optimizer.step()
        total_loss += loss.item()
    print(f"Epoch {epoch+1}, Loss: {total_loss/len(train_loader)}")

# Validation
model.eval()
valid_predictions, valid_labels = [], []

with torch.no_grad():
    for batch in valid_loader:
        input_ids, attention_mask, labels = batch
        outputs = model.generate(input_ids=input_ids, attention_mask=attention_mask)
        preds = [tokenizer.decode(g, skip_special_tokens=True) for g in outputs]
        valid_predictions.extend(preds)
        valid_labels.extend([tokenizer.decode(l, skip_special_tokens=True) for l in labels])

valid_predictions = [1 if p == "positive" else 0 for p in valid_predictions]
valid_labels = [1 if l == "positive" else 0 for l in valid_labels]

valid_accuracy = accuracy_score(valid_labels, valid_predictions)
print(f'Validation Accuracy: {valid_accuracy:.4f}')

# Topic modeling model
"""

# Load data using the function
train_df, valid_df, test_df = load_data(train_path, valid_path, test_path)

import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

def preprocess_text(text):
    if isinstance(text, str):
        text = text.lower()
        text = re.sub(r'\d+', '', text)
        text = re.sub(r'[^\w\s]', '', text)
        tokens = word_tokenize(text)
        stop_words = set(stopwords.words('english'))
        tokens = [word for word in tokens if word not in stop_words]
        lemmatizer = WordNetLemmatizer()
        tokens = [lemmatizer.lemmatize(word) for word in tokens]
        return ' '.join(tokens)
    return ''

# Apply preprocessing
train_df['cleaned_text'] = train_df['text'].apply(preprocess_text)
valid_df['cleaned_text'] = valid_df['text'].apply(preprocess_text)
test_df['cleaned_text'] = test_df['text'].apply(preprocess_text)
#train_df.head(50)

import gensim
from gensim import corpora
from gensim.models import CoherenceModel
import numpy as np

# Convert text data to bag-of-words format
def preprocess_for_gensim(texts):
    # Tokenize and preprocess text data
    return [word_tokenize(text.lower()) for text in texts]

# Convert to Gensim corpus
def create_corpus_and_dictionary(texts):
    tokenized_texts = preprocess_for_gensim(texts)
    dictionary = corpora.Dictionary(tokenized_texts)
    corpus = [dictionary.doc2bow(text) for text in tokenized_texts]
    return corpus, dictionary

# Calculate coherence score
def calculate_coherence_score(lda, corpus, dictionary):
    coherence_model = CoherenceModel(model=lda, texts=corpus, dictionary=dictionary, coherence='c_v')
    coherence_score = coherence_model.get_coherence()
    return coherence_score

# Prepare data for LDA
corpus_train, dictionary_train = create_corpus_and_dictionary(train_df['cleaned_text'])
corpus_valid, _ = create_corpus_and_dictionary(valid_df['cleaned_text'])

def train_lda_model(n_topics, corpus):
    lda = gensim.models.LdaModel(corpus, num_topics=n_topics, id2word=dictionary_train, passes=15, random_state=42)
    return lda

# Train LDA models with different numbers of topics and evaluate
topic_numbers = [2]  # Example topic numbers
lda_models = {}
for n_topics in topic_numbers:
    lda = train_lda_model(n_topics, corpus_train)
    lda_models[n_topics] = lda
    coherence = calculate_coherence_score(lda, corpus_valid, dictionary_train)
    print(f"Number of topics: {n_topics}, Coherence Score: {coherence}")

from sklearn.naive_bayes import MultinomialNB

def transform_text_to_topics(lda, corpus, num_topics):
    topic_matrix = np.zeros((len(corpus), num_topics))

    for i, doc in enumerate(corpus):
        doc_topics = lda.get_document_topics(doc, minimum_probability=0)
        for topic_num, prob in doc_topics:
            topic_matrix[i, topic_num] = prob

    return topic_matrix

def classify_sentiment(X_train_topic, y_train, X_valid_topic, y_valid):
    classifier = MultinomialNB()
    classifier.fit(X_train_topic, y_train)
    y_pred = classifier.predict(X_valid_topic)
    return y_pred

# Prepare data for LDA
corpus_train, dictionary_train = create_corpus_and_dictionary(train_df['cleaned_text'])
corpus_valid, _ = create_corpus_and_dictionary(valid_df['cleaned_text'])

# Train LDA models with different numbers of topics and evaluate
topic_numbers = [5, 10, 15, 20]  # Example topic numbers
lda_models = {}
for n_topics in topic_numbers:
    lda = train_lda_model(n_topics, corpus_train)
    lda_models[n_topics] = lda
    coherence = calculate_coherence_score(lda, corpus_valid, dictionary_train)
    print(f"Number of topics: {n_topics}, Coherence Score: {coherence}")

# Choose the best number of topics based on evaluation
best_n_topics = 10  # Update this based on evaluation results
best_lda = lda_models[best_n_topics]

# Convert text data to topics for training and validation sets
X_train_topics = transform_text_to_topics(best_lda, corpus_train, best_n_topics)
X_valid_topics = transform_text_to_topics(best_lda, corpus_valid, best_n_topics)

# Train and evaluate sentiment classifier
y_valid_pred = classify_sentiment(X_train_topics, train_df['sentiment'], X_valid_topics, valid_df['sentiment'])
print(print_performance_metrics(valid_df['sentiment'], y_valid_pred))

"""# BERT model"""

!pip install transformers

"""import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, Dataset
from transformers import BertTokenizer, BertForSequenceClassification, AdamW
from sklearn.metrics import accuracy_score
import pandas as pd

# Define custom dataset class
class SentimentDataset(Dataset):
    def __init__(self, texts, labels, tokenizer, max_len):
        self.texts = texts
        self.labels = labels
        self.tokenizer = tokenizer
        self.max_len = max_len

    def __len__(self):
        return len(self.texts)

    def __getitem__(self, index):
        text = self.texts[index]
        label = self.labels[index]

        encoding = self.tokenizer.encode_plus(
            text,
            add_special_tokens=True,
            max_length=self.max_len,
            return_token_type_ids=False,
            padding='max_length',
            truncation=True,
            return_attention_mask=True,
            return_tensors='pt',
        )

        return {
            'text': text,
            'input_ids': encoding['input_ids'].flatten(),
            'attention_mask': encoding['attention_mask'].flatten(),
            'label': torch.tensor(label, dtype=torch.long)
        }

# Load data
train_df = pd.read_csv('/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/train.csv')
valid_df = pd.read_csv('/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/valid.csv')
test_df = pd.read_csv('/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/test.csv')

# Preprocess text data
def preprocess_text(df, text_column):
    df['cleaned_text'] = df[text_column].str.lower()
    return df

# Remove rows with NaN values in 'text' column
train_df = train_df.dropna(subset=['text'])
valid_df = valid_df.dropna(subset=['text'])
test_df = test_df.dropna(subset=['text'])

# Preprocess text data
train_df = preprocess_text(train_df, text_column='text')
valid_df = preprocess_text(valid_df, text_column='text')
test_df = preprocess_text(test_df, text_column='text')

# Extract texts and labels
train_texts = train_df['cleaned_text'].tolist()
valid_texts = valid_df['cleaned_text'].tolist()
test_texts = test_df['cleaned_text'].tolist()

label_encoder = LabelEncoder()
y_train = label_encoder.fit_transform(train_df['sentiment'].tolist())
y_valid = label_encoder.transform(valid_df['sentiment'].tolist())

# Initialize tokenizer and model
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')
model = BertForSequenceClassification.from_pretrained('bert-base-uncased', num_labels=len(label_encoder.classes_))

# Set maximum length for BERT input
max_len = 160

# Create datasets and dataloaders
train_dataset = SentimentDataset(train_texts, y_train, tokenizer, max_len)
valid_dataset = SentimentDataset(valid_texts, y_valid, tokenizer, max_len)

train_loader = DataLoader(train_dataset, batch_size=16, shuffle=True)
valid_loader = DataLoader(valid_dataset, batch_size=16, shuffle=False)

# Define optimizer and loss function
optimizer = optim.AdamW(model.parameters(), lr=2e-5)
criterion = nn.CrossEntropyLoss()

# Training loop
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
model = model.to(device)

num_epochs = 3
for epoch in range(num_epochs):
    model.train()
    running_loss = 0.0
    for batch in train_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        optimizer.zero_grad()
        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        loss = criterion(outputs.logits, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item()

    print(f'Epoch [{epoch+1}/{num_epochs}], Loss: {running_loss/len(train_loader):.4f}')

# Validation
model.eval()
valid_predictions = []
valid_labels = []

with torch.no_grad():
    for batch in valid_loader:
        input_ids = batch['input_ids'].to(device)
        attention_mask = batch['attention_mask'].to(device)
        labels = batch['label'].to(device)

        outputs = model(input_ids=input_ids, attention_mask=attention_mask)
        _, preds = torch.max(outputs.logits, dim=1)
        valid_predictions.extend(preds.cpu().numpy())
        valid_labels.extend(labels.cpu().numpy())

valid_accuracy = accuracy_score(valid_labels, valid_predictions)
print(f'Validation Accuracy: {valid_accuracy:.4f}')

# Combaining the two models k-means with SVM
it is taking much time but i tried it with few parameters it workes and the result was 8.700 with the parameters 1, 0.1 and linear scale otherwise it takes tooo much time
"""

import pandas as pd
import re
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.cluster import KMeans
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import classification_report, accuracy_score
from sklearn.preprocessing import LabelEncoder
import pickle
from collections import Counter

# Download NLTK resources
nltk.download('stopwords')
nltk.download('punkt')

# Define preprocessing function
def preprocess_text(df, text_column='text'):
    """
    Preprocesses the text data in a DataFrame by:
    1. Handling missing values
    2. Cleaning text (lowercasing, removing digits, and punctuation)
    3. Tokenizing and removing stop words
    """
    # Fill missing values
    df[text_column] = df[text_column].fillna('')

    def clean_text(text):
        """Cleans the text by lowercasing, removing digits, and punctuation."""
        if isinstance(text, str):
            text = text.lower()
            text = re.sub(r'\d+', '', text)
            text = re.sub(r'[^\w\s]', '', text)
        return text

    df['cleaned_text'] = df[text_column].apply(clean_text)

    stop_words = set(stopwords.words('english'))

    def tokenize_and_filter(text):
        """Tokenizes the text and removes stop words."""
        tokens = word_tokenize(text)
        filtered_tokens = [word for word in tokens if word not in stop_words]
        return ' '.join(filtered_tokens)

    df['cleaned_text'] = df['cleaned_text'].apply(tokenize_and_filter)

    return df

# Load and preprocess data
train_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/train.csv'
valid_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/valid.csv'
test_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/data/15/test.csv'

train_df = pd.read_csv(train_path)
valid_df = pd.read_csv(valid_path)
test_df = pd.read_csv(test_path)

train_data = preprocess_text(train_df, text_column='text')
valid_data = preprocess_text(valid_df, text_column='text')
test_data = preprocess_text(test_df, text_column='text')

# Convert text data to TF-IDF features
vectorizer = TfidfVectorizer(stop_words='english')
train_unsup = vectorizer.fit_transform(train_data['cleaned_text'])
X_valid = vectorizer.transform(valid_data['cleaned_text'])
test_unsup = vectorizer.transform(test_data['cleaned_text'])

# Initialize and fit KMeans
kmeans = KMeans(n_clusters=2, random_state=42)
kmeans.fit(train_unsup)

# Predict clusters for all datasets
train_clusters = kmeans.predict(train_unsup)
valid_clusters = kmeans.predict(X_valid)
test_clusters = kmeans.predict(test_unsup)

# Convert to DataFrame and ensure all columns are strings
X_train_augmented = pd.DataFrame(train_unsup.toarray())
X_train_augmented['cluster'] = train_clusters
X_train_augmented.columns = X_train_augmented.columns.astype(str)  # Ensure column names are strings

X_valid_augmented = pd.DataFrame(X_valid.toarray())
X_valid_augmented['cluster'] = valid_clusters
X_valid_augmented.columns = X_valid_augmented.columns.astype(str)  # Ensure column names are strings

X_test_augmented = pd.DataFrame(test_unsup.toarray())
X_test_augmented['cluster'] = test_clusters
X_test_augmented.columns = X_test_augmented.columns.astype(str)  # Ensure column names are strings

# Extract labels for training SVM
y_train = train_df['sentiment']
y_valid = valid_df['sentiment']

# Define and train SVM model with Grid Search
svm = SVC(random_state=42)
param_grid = {
    'C': [0.9, 1, 1.1, 1.777],
    'kernel': ['linear', 'rbf'],
    'gamma': ['scale', 'auto']
}
grid_search = GridSearchCV(svm, param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_train_augmented, y_train)

# Get best model and evaluate
best_svm = grid_search.best_estimator_
y_valid_pred = best_svm.predict(X_valid_augmented)

print("Validation Accuracy:", accuracy_score(y_valid, y_valid_pred))
print("Validation Classification Report:\n", classification_report(y_valid, y_valid_pred))

# Save the best model and vectorizer
#model_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/model/2323135/Model_Dis/svm_model.pkl'
#vectorizer_path = '/content/gdrive/My Drive/CE807-24-SU/Assignment/model/2323135/Model_Dis/tfidf_vectorizer.pkl'
#with open(model_path, 'wb') as model_file:
    #pickle.dump(best_svm, model_file)
#with open(vectorizer_path, 'wb') as vectorizer_file:
    #pickle.dump(vectorizer, vectorizer_file)
print_performance_metrics(y_valid, y_valid_pred)



"""##Other Method/model End"""